application: rakontu
version: alpha-0-9-2
runtime: python
api_version: 1

handlers:

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /rocket/.*
  script: rocket/rocket.py

- url: /admin/.*
  script: main.py
  login: admin

- url: /images
  static_dir: images
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /javascript
  static_dir: javascript
  
- url: /.*
  script: main.py
