application: rakontu
version: alpha-0-9-0
runtime: python
api_version: 1

handlers:

- url: /rocket/.*
  script: rocket/rocket.py

- url: /admin/.*
  script: main.py
  login: admin

- url: /images
  static_dir: images
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /javascript
  static_dir: javascript
  
- url: /.*
  script: main.py
